package com.example.akshayshopapp.dataClass

import androidx.room.Entity
import androidx.room.PrimaryKey


//data class Product(
//    val id: Int,
//    val title: String,
//    val price: String?,
//    val category: String,
//    val description: String,
//    val image: String
//)



//ROOM DATABASE
@Entity(tableName = "cart_table")

data class Product(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0, //room will autogenerated
    val title: String,
    val price: String?,
    val category: String,
    val description: String,
    val image: String
)





